### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by tyeeman** [panyam/s3gen#1]
Nice having the tags feature. Are you still working on them. Their links don't work but I'm sure you know that.

**Comment by panyam** [comment]
Hey thanks for noticing.  Yep had been looking at a way for it.   Easiest would be to have another "custom" func but wanted to see if this was going to be useful and generic enough to be "standard".  Wdyt?

**Comment by tyeeman** [comment]
I would but I'm not a coder unfortunately.

**Comment by panyam** [comment]
Fixed.   Added extra page in the [personal blog](https://github.com/panyam/blog)

**Comment by tyeeman** [comment]
Thanks. I'm trying to install and get this error - 

```
go: github.com/panyam/s3gen@latest (in github.com/panyam/s3gen@v0.0.10):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

**Comment by panyam** [comment]
Hey @tyeeman are you trying to install s3gen or the blog?   My blog would be easier to install.  IL be creating a demo site with s3gen soon as part of this repo.

**Comment by tyeeman** [comment]
Yes,  I thought I was trying to install s3gen with that command line your readme mentioned.

```
go install github.com/panyam/s3gen@latest
```
I thought it would give me the same as https://buildmage.com/. I guess not. I will wait for s3gen.
